spring:
  config:
    import:
      - application-db.yml
      - application-oauth.yml

  jasypt:
    encryptor:
      password:
      bean: jasyptStringEncryptor

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

